### ISSUE TITLE
Reliance on processing order on the server

### ISSUE THREAD

**Issue by filipesmedeiros** [SyncFree/antidote_ts_client#4]
Judging by [this line](https://github.com/AntidoteDB/antidote_ts_client/blob/master/src/antidoteConnection.ts#L119), is it correct to assume that the TS client relies on the Antidote server processing and responding to requests in the same order it receives them (at least for the same client)?

**Comment by peterzeller** [comment]
Yes, your understanding is correct. 

We had some discussion of using [gRPC](https://grpc.io/) to make this more efficient.
